model_name: cbow

dataset: WikiText103
data_dir: data/
train_batch_size: 60
val_batch_size: 60
shuffle: True

optimizer: Adam
learning_rate: 0.025
epochs: 100
train_steps: 
val_steps: 

checkpoint_frequency: 
model_dir: weights/cbow_WikiText103
